@host = http://localhost:3333/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYTI3ZTQ5YS0xNjQ4LTQ1YjUtYjg0MS1iNjA2MzY4MmViNmEiLCJub21lIjoiQWRtaW4iLCJlbWFpbCI6ImFkbWluQGVtYWlsLmNvbSIsInBlcmZpbCI6IkFETUlOIiwiZXNjb3BvIjoiTE9DQUwiLCJlc3RhYmVsZWNpbWVudG9faWQiOiJkMzI0Njc0ZC1hNzk1LTQwYjgtODhhYi04ODVhZDExZmI1ZTIiLCJlbXByZXNhX2lkIjpudWxsLCJpYXQiOjE3NzU3NDA3NjAsImV4cCI6MTc3NjM0NTU2MH0.8QXvxU4D4UhEwvBeo598tr-3MZPbiSvshO4EB_37wDM

# @name login
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "adminglobal@email.com",
  "senha": "novaSenha123"
}


### Login
# @name login
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "admin@email.com",
  "senha": "novaSenha123"
}

###

GET {{host}}/auth/me
Authorization: Bearer {{token}}

### Esqueci minha senha
POST {{host}}/auth/esqueci-senha
Content-Type: application/json

{
  "email": "adminglobal@email.com"
}

###

### Redefinir senha
### Copie o token do banco pelo Prisma Studio:
### npm run prisma:studio → tabela tokens_recuperacao_senha
POST {{host}}/auth/redefinir-senha
Content-Type: application/json

{
  "token": "195e50bead43dabaeac32c6938e80b8de11ddc7ce543e1f36a3e75a3e05cbb5f",
  "nova_senha": "novaSenha123",
  "confirmar_senha": "novaSenha123"
}