@host = http://localhost:3333/api/v1

### Solicitar recuperação de senha
# @name passwordReset
POST {{host}}/auth/passwordReset
Content-Type: application/json

{
  "email": "admin@email.com"
}

###
@resetToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYTI3ZTQ5YS0xNjQ4LTQ1YjUtYjg0MS1iNjA2MzY4MmViNmEiLCJub21lIjoiQWRtaW4iLCJlbWFpbCI6ImFkbWluQGVtYWlsLmNvbSIsInBlcmZpbCI6IkFETUlOIiwiZXNjb3BvIjoiTE9DQUwiLCJlc3RhYmVsZWNpbWVudG9faWQiOiJkMzI0Njc0ZC1hNzk1LTQwYjgtODhhYi04ODVhZDExZmI1ZTIiLCJlbXByZXNhX2lkIjpudWxsLCJpYXQiOjE3NzU0ODE2NTksImV4cCI6MTc3NjA4NjQ1OX0.latH3JZQhe6cLeep74RB03TxZmB4y3JXhIn6RGLy3K4


### Resetar senha
# @name resetPassword
POST {{host}}/auth/reset-password
Content-Type: application/json

{
  "token": "{{resetToken}}",
  "novaSenha": "novaSenha123"
}


### Testar login com nova senha
# @name loginWithNewPassword
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "admin@email.com",
  "senha": "novaSenha123"
}