@host = http://localhost:3333/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyN2MwNGI1Zi04NzViLTRkZmEtYmVkMy1hNWFiNjg2NTYwYmIiLCJub21lIjoiQWRtaW5nbG9iYWwiLCJlbWFpbCI6ImFkbWluZ2xvYmFsQGVtYWlsLmNvbSIsInBlcmZpbCI6IkFETUlOIiwiZXNjb3BvIjoiR0xPQkFMIiwiZXN0YWJlbGVjaW1lbnRvX2lkIjoiMTIwZDNjMWMtZmI5Yi00MGQ0LWJlYjItNzU5M2IzMzhiODBlIiwiZW1wcmVzYV9pZCI6bnVsbCwiaWF0IjoxNzgwMzE2NDMwLCJleHAiOjE3ODA5MjEyMzB9.2YoZw6ywHBF17R9pc_50XgTzFFOj4goCZKK5nXjQwCI
POST {{host}}/usuarios
Content-Type: application/json

{
  "nome": "Admin",
  "email": "admin@email.com",
  "senha": "senha123",
  "perfil": "ADMIN",
  "escopo": "LOCAL",
  "estabelecimento_id": "ID_DO_ESTABELECIMENTO_AQUI"
}

###

POST {{host}}/usuarios
Content-Type: application/json

{
  "nome": "Teste3",
  "email": "leticiaquadre@email.com",
  "senha": "senha123!",
  "perfil": "ADMIN",
  "escopo": "LOCAL",
  "estabelecimento_id": "120d3c1c-fb9b-40d4-beb2-7593b338b80e"
}

###

GET {{host}}/usuarios
Content-Type: application/json
Authorization: Bearer {{token}}